spring.datasource.url=${MEETBOWL_DB_URL:jdbc:mariadb://localhost:3309/meetbowl}
spring.datasource.username=${MEETBOWL_DB_USERNAME:meetbowl}
spring.datasource.password=${MEETBOWL_DB_PASSWORD:thanos123}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
