spring.datasource.url=${MEETBOWL_DB_URL}
spring.datasource.username=${MEETBOWL_DB_USERNAME}
spring.datasource.password=${MEETBOWL_DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
